### PR TITLE
Add dial timeout

### PR DESCRIPTION
**Pull request by practice-golang**
Some service provider block personal ip address and some do not give any response.
In my case, naver.com act as waiting villain.

### CODE REVIEW

**Review by nilslice — CHANGES_REQUESTED** [review]
Good idea! To accept this PR, I would prefer that the timeout is passed in to Send, via a context. 

Please let me know if you disagree. I'm imagining that you'd set up your Message, then your context.WithTimeout, and then call msg.Send(ctx), where your dialTimeout func gets the timeout from the context. 

You could alternatively add a separate method SendContext(ctx) so there is no API change.

**Comment by practice-golang** [comment]
Hello @nilslice , sorry for late response.
Ok, I will PR again

**Comment by practice-golang** [comment]
Hello @nilslice , I requested PR again, could you please check this?

BTW, I'm not sure which is better using context or using variable(not a struct).
I'v tried to wrap context definition code into SendContext function but did not work.

Thank you 😄

**Comment by nilslice** [comment]
Hi, I'm closing this after opening a new PR using your branch as a base. See https://github.com/nilslice/email/pull/4 for more details. Thank you!

**Pull request closed without merging**
